// Per-island buyer's-guide copy (trilingual). Unique, substantive content so the
// category/island landing pages are not "thin" — each explains what the island is,
// who buys there and the checks to make, always co-occurring "Cabo Verde" for
// search disambiguation (São Vicente/Mindelo/Cabo Verde also exist in Brazil/PT).
import type { TL } from '@/i18n';

export interface IslandGuide {
  slug: string;        // URL area segment, e.g. 'sao-vicente'
  name: string;        // exact island name as stored on listings/professionals/suppliers
  code: string;        // listing island code used by filterListings (SV/ST/SL/BV)
  intro: TL;           // one-paragraph lede
  body: TL;            // two paragraphs, separated by "\n\n"
}

export const ISLAND_GUIDES: IslandGuide[] = [
  {
    slug: 'sao-vicente',
    name: 'São Vicente',
    code: 'SV',
    intro: {
      pt: 'São Vicente é amplamente considerada o coração cultural de Cabo Verde, com destaque para a animada cidade portuária do Mindelo. Conhecida pela música, pelo Carnaval e pela sua vida criativa, a ilha combina energia urbana com um ambiente à beira-mar fácil de percorrer a pé.',
      en: 'São Vicente is widely regarded as the cultural heart of Cabo Verde, centred on the lively port city of Mindelo. Known for its music, Carnival and creative scene, the island pairs urban energy with a walkable, harbour-side setting.',
      nl: 'São Vicente geldt als het culturele hart van Kaapverdië, met als middelpunt de levendige havenstad Mindelo. Bekend om zijn muziek, carnaval en creatieve scene, combineert het eiland stedelijke energie met een goed beloopbare ligging aan zee.',
    },
    body: {
      pt: 'São Vicente é sobretudo conhecida como o berço da morna e da cantora Cesária Évora, que dá nome ao aeroporto da ilha, junto a São Pedro. A vida gira em torno do Mindelo, a principal cidade da ilha, cujas ruas coloniais coloridas, marina e baía do Porto Grande atraem um fluxo constante de visitantes. O Mindelo é também a porta de entrada, por ferry, para a vizinha Santo Antão, que não tem aeroporto próprio.\n\nQuem compra aqui procura, em geral, um estilo de vida ligado às artes, à cultura de esplanada e ao mar, muitas vezes um apartamento na cidade, uma casa antiga recuperada ou uma segunda habitação, mais do que uma unidade de resort. Face às ilhas balneares, o mercado é mais urbano e menos sazonal. Antes de avançar, confirme o título e o registo do imóvel, o imposto de transmissão (cITI) e o imposto sobre o património (cIPI), bem como eventuais licenças de construção, junto de um notário e das entidades oficiais competentes.',
      en: "São Vicente is best known as the home of morna music and the late singer Cesária Évora, after whom the island's airport near São Pedro is named. Life revolves around Mindelo, the island's main city, whose colourful colonial streets, marina and Porto Grande bay draw a steady stream of visitors. Mindelo is also the ferry gateway to neighbouring Santo Antão, which has no airport of its own.\n\nBuyers here tend to be lifestyle-oriented: people drawn to the arts, the café culture and the sea, often looking for a city apartment, a restored townhouse or a second home rather than a resort unit. Compared with the beach islands, the market feels more urban and year-round than seasonal. Before committing, confirm the property's title and registration, the transfer tax (cITI) and annual property tax (cIPI), and any building or renovation permits with a notary and the relevant official bodies.",
      nl: 'São Vicente staat vooral bekend als de bakermat van de mornamuziek en van zangeres Cesária Évora, naar wie de luchthaven van het eiland bij São Pedro is vernoemd. Het leven speelt zich af in Mindelo, de hoofdstad van het eiland, waarvan de kleurrijke koloniale straten, de jachthaven en de baai Porto Grande een gestage stroom bezoekers trekken. Mindelo is ook de veerbootverbinding naar het naburige Santo Antão, dat zelf geen luchthaven heeft.\n\nKopers hier zijn vooral gericht op levensstijl: mensen die worden aangetrokken door kunst, terrascultuur en de zee, vaak op zoek naar een stadsappartement, een gerenoveerd herenhuis of een tweede woning in plaats van een resortunit. Vergeleken met de strandeilanden voelt de markt stedelijker en minder seizoensgebonden. Controleer vóór aankoop de eigendomstitel en registratie, de overdrachtsbelasting (cITI) en de onroerendgoedbelasting (cIPI), en eventuele bouwvergunningen bij een notaris en de bevoegde officiële instanties.',
    },
  },
  {
    slug: 'sal',
    name: 'Sal',
    code: 'SL',
    intro: {
      pt: 'Sal é a ilha turística mais consolidada de Cabo Verde e uma das suas principais portas de entrada internacionais, graças ao Aeroporto Internacional Amílcar Cabral. Plana, soalheira e rodeada por praias de areia branca, é a ilha mais associada a férias e escapadinhas.',
      en: 'Sal is Cabo Verde’s most established tourism island and one of its main international gateways, thanks to Amílcar Cabral International Airport. Flat, sunny and ringed by white-sand beaches, it is the island most associated with holidays and short breaks.',
      nl: 'Sal is het meest ontwikkelde toerisme-eiland van Kaapverdië en een van de belangrijkste internationale toegangspoorten, dankzij de internationale luchthaven Amílcar Cabral. Vlak, zonnig en omringd door witte zandstranden is het het eiland dat het sterkst met vakanties en korte trips wordt geassocieerd.',
    },
    body: {
      pt: 'A ilha tem dois centros: Espargos, a povoação administrativa junto ao aeroporto, e Santa Maria, a vila balnear no extremo sul onde se concentra a maior parte do turismo. Sal é conhecida pelas longas praias de areia, pelos desportos aquáticos como o windsurf, o kitesurf e o mergulho, e pela cratera de sal de Pedra de Lume, num vulcão extinto. Grande parte da construção costeira situa-se em zonas de desenvolvimento turístico (ZDTI), incluindo Santa Maria, Pedra de Lume e Murdeira.\n\nOs compradores procuram sobretudo casas de férias e investimentos para arrendamento — apartamentos, unidades em resort e moradias — e Santa Maria tem uma comunidade internacional e de expatriados bem visível. Como a procura está muito ligada ao turismo, o potencial de arrendamento e a proximidade da praia pesam tanto como o próprio imóvel. Antes de comprar, verifique o título e o registo, o imposto de transmissão (cITI) e o imposto sobre o património (cIPI), e eventuais licenças de construção, junto de um notário e das autoridades oficiais.',
      en: 'The island has two centres: Espargos, the administrative town beside the airport, and Santa Maria, the beach resort town on the southern tip that is the focus of most tourism. Sal is known for long sandy beaches, watersports such as windsurfing, kitesurfing and diving, and the Pedra de Lume salt crater set in an extinct volcano. Much of the coastal development sits within designated tourism zones (ZDTI), including Santa Maria, Pedra de Lume and Murdeira.\n\nBuyers here are typically after holiday homes and rental investments — apartments, resort units and villas — and Santa Maria has a visible international and expat community. Because demand is closely tied to tourism, rental potential and location relative to the beach often matter as much as the property itself. Before buying, verify the title and registration, the transfer tax (cITI) and property tax (cIPI), and any building permits through a notary and the official authorities.',
      nl: 'Het eiland heeft twee centra: Espargos, de bestuurlijke plaats naast de luchthaven, en Santa Maria, de badplaats op de zuidpunt waar het grootste deel van het toerisme zich concentreert. Sal staat bekend om zijn lange zandstranden, watersporten zoals windsurfen, kitesurfen en duiken, en de zoutkrater Pedra de Lume in een uitgedoofde vulkaan. Een groot deel van de kustontwikkeling ligt binnen aangewezen toerismezones (ZDTI), waaronder Santa Maria, Pedra de Lume en Murdeira.\n\nKopers zoeken hier vooral vakantiewoningen en beleggingen voor verhuur — appartementen, resortunits en villa’s — en Santa Maria heeft een zichtbare internationale en expatgemeenschap. Omdat de vraag nauw samenhangt met toerisme, wegen het verhuurpotentieel en de ligging ten opzichte van het strand vaak net zo zwaar als de woning zelf. Controleer vóór aankoop de eigendomstitel en registratie, de overdrachtsbelasting (cITI) en de onroerendgoedbelasting (cIPI), en eventuele bouwvergunningen bij een notaris en de officiële instanties.',
    },
  },
  {
    slug: 'santiago',
    name: 'Santiago',
    code: 'ST',
    intro: {
      pt: 'Santiago é a maior e mais populosa ilha de Cabo Verde e alberga a Praia, capital do país. Oferece as paisagens mais variadas do arquipélago — montanhas, vales férteis e praias — a par do seu papel de principal centro económico e administrativo.',
      en: "Santiago is the largest and most populous island in Cabo Verde and home to Praia, the national capital. It offers the country's most varied landscapes — mountains, fertile valleys and beaches — alongside its role as the main business and government hub.",
      nl: 'Santiago is het grootste en dichtstbevolkte eiland van Kaapverdië en de thuisbasis van Praia, de hoofdstad van het land. Het biedt de meest gevarieerde landschappen van de archipel — bergen, vruchtbare valleien en stranden — naast zijn rol als belangrijkste economische en bestuurlijke centrum.',
    },
    body: {
      pt: 'É em Santiago que se concentra grande parte da vida quotidiana, do comércio e da administração de Cabo Verde, o que lhe dá um carácter mais local e menos sazonal do que as ilhas de resort. A Praia, a capital, é a maior cidade do país e o seu centro económico, com um núcleo histórico no Plateau e bairros residenciais em expansão. A vizinha Cidade Velha (Ribeira Grande de Santiago), o primeiro povoado europeu nos trópicos, é Património Mundial da UNESCO, enquanto localidades como Assomada, no interior, e Tarrafal, a norte, acrescentam variedade rural e costeira.\n\nQuem compra aqui inclui frequentemente pessoas que se mudam por trabalho, membros da diáspora que regressam e quem procura residência principal, mais do que arrendamento de férias, pelo que a procura tende para apartamentos e casas de família. O investimento acompanha sobretudo o crescimento urbano da Praia, e não o turismo balnear. Antes da compra, verifique o título e o registo do imóvel, o imposto de transmissão (cITI) e o imposto sobre o património (cIPI), e eventuais licenças de construção, junto de um notário e das entidades competentes.',
      en: "Santiago is where much of Cabo Verde's daily life, commerce and administration is concentrated, giving it a more local and year-round character than the resort islands. Praia, the capital, is the country's largest city and its economic centre, with a historic core on the Plateau and expanding residential neighbourhoods. Nearby Cidade Velha (Ribeira Grande de Santiago), the first European settlement in the tropics, is a UNESCO World Heritage Site, while towns such as Assomada in the interior and Tarrafal in the north add rural and coastal variety.\n\nBuyers here often include people relocating for work, returning diaspora and those seeking a primary residence rather than a holiday let, so demand leans toward city apartments and family homes. Investment tends to follow urban growth around Praia rather than beach tourism. Before purchase, check the property's title and registration, the transfer tax (cITI) and property tax (cIPI), and any building permits with a notary and the competent authorities.",
      nl: 'Op Santiago speelt zich een groot deel van het dagelijks leven, de handel en het bestuur van Kaapverdië af, wat het eiland een lokaler en minder seizoensgebonden karakter geeft dan de resorteilanden. Praia, de hoofdstad, is de grootste stad van het land en het economische centrum, met een historische kern op het Plateau en groeiende woonwijken. Het nabijgelegen Cidade Velha (Ribeira Grande de Santiago), de eerste Europese nederzetting in de tropen, staat op de Werelderfgoedlijst van UNESCO, terwijl plaatsen als Assomada in het binnenland en Tarrafal in het noorden voor landelijke en kustvariatie zorgen.\n\nKopers hier zijn vaak mensen die voor hun werk verhuizen, terugkerende diaspora en wie een hoofdverblijf zoekt in plaats van vakantieverhuur, waardoor de vraag neigt naar stadsappartementen en gezinswoningen. Investeringen volgen vooral de stedelijke groei rond Praia, en niet het strandtoerisme. Controleer vóór aankoop de eigendomstitel en registratie, de overdrachtsbelasting (cITI) en de onroerendgoedbelasting (cIPI), en eventuele bouwvergunningen bij een notaris en de bevoegde autoriteiten.',
    },
  },
  {
    slug: 'boa-vista',
    name: 'Boa Vista',
    code: 'BV',
    intro: {
      pt: 'Boa Vista é a terceira maior ilha de Cabo Verde e um dos seus principais destinos de praia, conhecida pelas vastas areias brancas e pelas dunas de aspeto saariano. A sua capital, Sal Rei, junta a tranquilidade de uma vila insular ao fácil acesso ao litoral dos resorts.',
      en: "Boa Vista is Cabo Verde's third-largest island and one of its main beach destinations, known for vast white-sand shores and Sahara-like dunes. Its capital, Sal Rei, combines a relaxed island town with easy access to the resort coast.",
      nl: 'Boa Vista is het op twee na grootste eiland van Kaapverdië en een van de belangrijkste strandbestemmingen, bekend om zijn uitgestrekte witte zandstranden en Sahara-achtige duinen. Hoofdplaats Sal Rei combineert een ontspannen eilandstadje met gemakkelijke toegang tot de resortkust.',
    },
    body: {
      pt: 'A ilha tem um ambiente selvagem e desértico — as dunas de Viana, longas praias quase desertas como a Praia de Chaves e Santa Mónica, e um dos mais importantes locais de nidificação de tartarugas-comuns do Atlântico. Sal Rei é a principal povoação, com arquitetura colonial, mercados locais e uma frente de mar, enquanto o Aeroporto Internacional Aristides Pereira, junto a Rabil, recebe voos diretos de várias cidades europeias. Grande parte da construção costeira situa-se em zonas de desenvolvimento turístico (ZDTI), organizadas em torno de grandes resorts à beira-mar.\n\nTal como Sal, Boa Vista atrai sobretudo compradores de casas de férias e de investimento, interessados em apartamentos, moradias e unidades de resort, muitas vezes com vista ao arrendamento. Como a economia é fortemente assente no turismo, a proximidade da praia, os acessos e a procura de arrendamento são fatores decisivos. Antes de comprar, confirme o título e o registo, o imposto de transmissão (cITI) e o imposto sobre o património (cIPI), e eventuais licenças de construção, junto de um notário e das autoridades oficiais competentes.',
      en: "The island has a wild, desert feel — the Viana dunes, long empty beaches such as Praia de Chaves and Santa Mónica, and one of the Atlantic's most important loggerhead turtle nesting sites. Sal Rei is the main town, with colonial architecture, local markets and a seafront, while Aristides Pereira International Airport near Rabil brings direct flights from several European cities. Much of the coastal development sits within designated tourism zones (ZDTI) built around large beachfront resorts.\n\nLike Sal, Boa Vista mainly attracts holiday-home and investment buyers looking at apartments, villas and resort units, often with rental use in mind. Because the economy is heavily tourism-led, beach proximity, access and rental demand are key considerations. Before buying, confirm the title and registration, the transfer tax (cITI) and annual property tax (cIPI), and any building permits with a notary and the relevant official authorities.",
      nl: 'Het eiland heeft een wild, woestijnachtig karakter — de duinen van Viana, lange, vrijwel lege stranden zoals Praia de Chaves en Santa Mónica, en een van de belangrijkste nestplaatsen voor onechte karetschildpadden in de Atlantische Oceaan. Sal Rei is de hoofdplaats, met koloniale architectuur, lokale markten en een zeeboulevard, terwijl de internationale luchthaven Aristides Pereira bij Rabil directe vluchten uit verschillende Europese steden ontvangt. Een groot deel van de kustontwikkeling ligt binnen aangewezen toerismezones (ZDTI), opgebouwd rond grote strandresorts.\n\nNet als Sal trekt Boa Vista vooral kopers van vakantiewoningen en beleggers aan, die kijken naar appartementen, villa’s en resortunits, vaak met het oog op verhuur. Omdat de economie sterk op toerisme leunt, zijn de nabijheid van het strand, de bereikbaarheid en de verhuurvraag doorslaggevende factoren. Controleer vóór aankoop de eigendomstitel en registratie, de overdrachtsbelasting (cITI) en de jaarlijkse onroerendgoedbelasting (cIPI), en eventuele bouwvergunningen bij een notaris en de bevoegde officiële instanties.',
    },
  },
];
