-- 0008 — refresh + expand official info-centre seeds.
-- Upserts richer, sourced summaries for the two 0006 items and adds two new
-- topics (tenancy basics, buying steps). Idempotent: on conflict updates in place.
-- All content is a PLATFORM SUMMARY, not official info — reliability is marked
-- inline and legal verification is required. Run after 0006.

insert into public.publications (slug, category, title, gov_entity, official_status, version, source_url, summary, body, status, published_at)
values
(
  'inquilino-recusa-sair', 'arrendamento',
  '{"pt":"Inquilino que se recusa a sair: o que pode fazer o senhorio","en":"Tenant who refuses to leave: what a landlord can do","nl":"Huurder die weigert te vertrekken: wat kan de verhuurder doen"}'::jsonb,
  'Resumo da plataforma — validacao juridica necessaria', 'summary', 2, 'https://boe.incv.cv/',
  '{"pt":"Resumo indicativo. O senhorio nao pode despejar pela forca nem por meios proprios: a saida resolve-se por via judicial (acao de despejo). O arrendamento urbano rege-se pela Lei n.o 101/VIII/2016 (Regime Geral do Arrendamento Urbano) e pelo Codigo Civil. Recomenda-se advogado.","en":"Indicative summary. A landlord may not evict by force or self-help: removal is resolved through the courts (eviction claim). Urban tenancy is governed by Law 101/VIII/2016 (General Urban Tenancy Regime) and the Civil Code. A lawyer is recommended.","nl":"Indicatieve samenvatting. Een verhuurder mag niet met geweld of eigenmachtig ontruimen: vertrek verloopt via de rechter (ontruimingsvordering). Stedelijke huur valt onder Wet 101/VIII/2016 en het Burgerlijk Wetboek. Een advocaat wordt aangeraden."}'::jsonb,
  '{"pt":"Passos gerais e indicativos (nao constituem aconselhamento juridico):\n\n1) Comunicar por escrito ao inquilino a cessacao do contrato, respeitando os prazos legais.\n2) Se o inquilino nao sair no prazo, procurar aconselhamento juridico.\n3) Instaurar a acao de despejo no tribunal competente, pedindo a entrega do imovel.\n4) NUNCA trocar fechaduras, cortar agua/luz ou retirar bens por conta propria — e ilegal.\n5) Confirmar procedimento, prazos e requisitos no Boletim Oficial e com um advogado.\n\nBase legal citada (FACTO, a confirmar): Lei n.o 101/VIII/2016, de 6 de janeiro; Codigo Civil. Verificacao juridica necessaria.","en":"General, indicative steps (not legal advice):\n\n1) Notify the tenant in writing of the termination, respecting statutory notice periods.\n2) If the tenant does not leave in time, seek legal advice.\n3) Bring an eviction claim before the competent court, requesting return of the property.\n4) NEVER change locks, cut water/power or remove belongings yourself — it is unlawful.\n5) Confirm procedure, deadlines and requirements in the Official Gazette and with a lawyer.\n\nCited legal basis (FACT, to be confirmed): Law 101/VIII/2016 of 6 January; Civil Code. Legal verification required.","nl":"Algemene, indicatieve stappen (geen juridisch advies):\n\n1) Informeer de huurder schriftelijk over de beeindiging, met inachtneming van de wettelijke termijnen.\n2) Vertrekt de huurder niet op tijd, win dan juridisch advies in.\n3) Start een ontruimingsvordering bij de bevoegde rechter en vorder teruggave van het pand.\n4) Verander NOOIT zelf de sloten, sluit geen water/stroom af en verwijder geen spullen — dat is onwettig.\n5) Bevestig procedure, termijnen en vereisten in het Boletim Oficial en bij een advocaat.\n\nAangehaalde rechtsgrond (FEIT, te bevestigen): Wet 101/VIII/2016 van 6 januari; Burgerlijk Wetboek. Juridische verificatie vereist."}'::jsonb,
  'published', now()
),
(
  'reforma-fiscal-imobiliaria-2026', 'impostos',
  '{"pt":"Reforma fiscal imobiliaria 2026: fim do IUP, entram o ITI e o IPI","en":"2026 real-estate tax reform: IUP ends, ITI and IPI begin","nl":"Vastgoedbelastinghervorming 2026: einde IUP, komst ITI en IPI"}'::jsonb,
  'Resumo da plataforma — confirmar com a Autoridade Tributaria', 'summary', 2, 'https://boe.incv.cv/',
  '{"pt":"Desde 1 de janeiro de 2026 o IUP foi substituido por dois impostos: o ITI (Imposto sobre a Transmissao de Imoveis) e o IPI (Imposto sobre a Propriedade de Imoveis). Confirmar taxas e isencoes com a Autoridade Tributaria.","en":"Since 1 January 2026 the IUP has been replaced by two taxes: ITI (property Transfer tax) and IPI (property Ownership tax). Confirm rates and exemptions with the tax authority.","nl":"Sinds 1 januari 2026 is de IUP vervangen door twee belastingen: de ITI (overdrachtsbelasting) en de IPI (eigendomsbelasting). Bevestig tarieven en vrijstellingen bij de Belastingdienst."}'::jsonb,
  '{"pt":"O que mudou (FACTO, fontes abaixo):\n\n• ITI — Imposto sobre a Transmissao de Imoveis (codigo cITI), aprovado pela Lei n.o 54/X/2025, publicada em 6 de junho de 2025. Taxa geral indicada: 1%, subindo para 3% quando uma das partes beneficia de tratamento fiscal privilegiado.\n• IPI — Imposto sobre a Propriedade de Imoveis (codigo cIPI), aprovado pela Lei n.o 55/X/2025. Taxa geral indicada: 0,1%; terrenos 0,15%; taxas mais altas para predios devolutos, em ruina ou urbanizacao incompleta.\n• Entrada em vigor: 1 de janeiro de 2026.\n\nEstas taxas sao indicativas e podem ter isencoes ou atualizacoes. Confirme os valores em vigor com a Autoridade Tributaria e no Boletim Oficial. Resumo informativo — nao substitui informacao oficial.\n\nFontes: PwC (flash fiscal Cabo Verde, 2025); Boletim Oficial. Verificacao necessaria.","en":"What changed (FACT, sources below):\n\n• ITI — property Transfer tax (code cITI), approved by Law 54/X/2025, published 6 June 2025. Indicated standard rate: 1%, rising to 3% when a party benefits from privileged tax treatment.\n• IPI — property Ownership tax (code cIPI), approved by Law 55/X/2025. Indicated general rate: 0.1%; land 0.15%; higher rates for vacant, ruined or incomplete-development buildings.\n• Entry into force: 1 January 2026.\n\nThese rates are indicative and may carry exemptions or updates. Confirm the rates in force with the tax authority and in the Official Gazette. Informational summary — does not replace official information.\n\nSources: PwC (Cape Verde tax flash, 2025); Official Gazette. Verification required.","nl":"Wat er veranderde (FEIT, bronnen hieronder):\n\n• ITI — overdrachtsbelasting (code cITI), goedgekeurd bij Wet 54/X/2025, gepubliceerd op 6 juni 2025. Aangegeven algemeen tarief: 1%, oplopend tot 3% als een partij een fiscaal voordeel geniet.\n• IPI — eigendomsbelasting (code cIPI), goedgekeurd bij Wet 55/X/2025. Aangegeven algemeen tarief: 0,1%; grond 0,15%; hogere tarieven voor leegstaande, vervallen of onvoltooide gebouwen.\n• Inwerkingtreding: 1 januari 2026.\n\nDeze tarieven zijn indicatief en kunnen vrijstellingen of updates kennen. Bevestig de geldende tarieven bij de Belastingdienst en in het Boletim Oficial. Informatieve samenvatting — vervangt geen officiele informatie.\n\nBronnen: PwC (fiscale flash Kaapverdie, 2025); Boletim Oficial. Verificatie vereist."}'::jsonb,
  'published', now()
),
(
  'arrendamento-regras-basicas', 'arrendamento',
  '{"pt":"Arrendamento urbano: regras basicas do contrato","en":"Urban tenancy: basic contract rules","nl":"Stedelijke huur: basisregels van het contract"}'::jsonb,
  'Resumo da plataforma — validacao juridica necessaria', 'summary', 1, 'https://boe.incv.cv/',
  '{"pt":"O arrendamento urbano rege-se pela Lei n.o 101/VIII/2016 (RGAU). Pontos indicados: contrato por escrito em tres vias, duracao supletiva de 6 meses e contratos de duracao limitada nao inferiores a 3 anos na habitacao. Confirmar antes de assinar.","en":"Urban tenancy is governed by Law 101/VIII/2016 (RGAU). Indicated points: written contract in three copies, a default term of 6 months, and limited-term residential contracts of not less than 3 years. Confirm before signing.","nl":"Stedelijke huur valt onder Wet 101/VIII/2016 (RGAU). Aangegeven punten: schriftelijk contract in drie exemplaren, standaardduur van 6 maanden en huurcontracten van bepaalde duur van minimaal 3 jaar voor bewoning. Bevestig voor ondertekening."}'::jsonb,
  '{"pt":"Pontos indicativos do Regime Geral do Arrendamento Urbano (FACTO, a confirmar no Boletim Oficial):\n\n• O contrato deve ser celebrado por escrito e, segundo as fontes, elaborado em tres vias.\n• Na falta de prazo estipulado, aplica-se uma duracao supletiva de 6 meses.\n• E permitida a antecipacao de rendas.\n• Nos arrendamentos habitacionais sao possiveis contratos de duracao limitada nao inferior a 3 anos.\n• A cessacao pode ocorrer por acordo, resolucao, caducidade ou denuncia, nos termos da lei.\n\nO contrato pro-forma gerado pela Djarvista e apenas uma ferramenta de apoio (self-service). A Djarvista nao e parte, advogado nem controlador juridico do contrato. Confirme sempre com um advogado e no Boletim Oficial.\n\nFonte citada: Lei n.o 101/VIII/2016, de 6 de janeiro. Verificacao juridica necessaria.","en":"Indicative points of the General Urban Tenancy Regime (FACT, to confirm in the Official Gazette):\n\n• The contract must be made in writing and, per the sources, drawn up in three copies.\n• Absent a stipulated term, a default duration of 6 months applies.\n• Advance payment of rent is permitted.\n• For residential lets, limited-term contracts of not less than 3 years are possible.\n• Termination may occur by agreement, resolution, lapse or notice, under the law.\n\nThe pro-forma contract generated by Djarvista is only a self-service support tool. Djarvista is not a party, lawyer or legal controller of the contract. Always confirm with a lawyer and in the Official Gazette.\n\nCited source: Law 101/VIII/2016 of 6 January. Legal verification required.","nl":"Indicatieve punten van het Algemeen Regime Stedelijke Huur (FEIT, te bevestigen in het Boletim Oficial):\n\n• Het contract moet schriftelijk zijn en, volgens de bronnen, in drie exemplaren worden opgesteld.\n• Zonder afgesproken termijn geldt een standaardduur van 6 maanden.\n• Vooruitbetaling van huur is toegestaan.\n• Voor bewoning zijn contracten van bepaalde duur van minimaal 3 jaar mogelijk.\n• Beeindiging kan via overeenkomst, ontbinding, verval of opzegging, volgens de wet.\n\nHet pro-forma contract van Djarvista is slechts een self-service hulpmiddel. Djarvista is geen partij, advocaat of juridisch controleur van het contract. Bevestig altijd bij een advocaat en in het Boletim Oficial.\n\nAangehaalde bron: Wet 101/VIII/2016 van 6 januari. Juridische verificatie vereist."}'::jsonb,
  'published', now()
),
(
  'comprar-imovel-passos', 'compra',
  '{"pt":"Comprar um imovel em Cabo Verde: passos principais","en":"Buying a property in Cape Verde: the main steps","nl":"Een woning kopen in Kaapverdie: de belangrijkste stappen"}'::jsonb,
  'Resumo da plataforma — fontes comerciais, nao oficiais', 'summary', 1, 'https://boe.incv.cv/',
  '{"pt":"Passos habituais: obter NIF, verificar a certidao de registo predial, assinar o contrato-promessa, celebrar a escritura publica perante notario e registar a propriedade. Ha custos de imposto de transmissao (ITI), notario e registo. Nao e aconselhamento juridico.","en":"Typical steps: obtain a tax number (NIF), check the land-registry certificate, sign the promissory contract, execute the public deed before a notary, and register the property. There are transfer-tax (ITI), notary and registration costs. Not legal advice.","nl":"Gebruikelijke stappen: verkrijg een fiscaal nummer (NIF), controleer het kadastrale uittreksel, teken het voorlopige koopcontract, verlijd de notariele akte en schrijf de eigendom in. Er zijn kosten voor overdrachtsbelasting (ITI), notaris en inschrijving. Geen juridisch advies."}'::jsonb,
  '{"pt":"Sequencia indicativa (ASSUNCAO com base em guias comerciais — confirmar):\n\n1) Obter o NIF (Numero de Identificacao Fiscal) nas Financas. Estrangeiros podem comprar imoveis em Cabo Verde.\n2) Pedir a Certidao de Registo Predial na Conservatoria para verificar a descricao do imovel e eventuais onus/hipotecas.\n3) Recomendavel: constituir procuracao a um advogado cabo-verdiano.\n4) Assinar o Contrato-Promessa de Compra e Venda (sinal habitual de 10–30%).\n5) Celebrar a Escritura Publica perante notario e pagar o remanescente.\n6) Registar a propriedade em seu nome no Registo Predial.\n\nCustos aproximados (INDICATIVO): transmissao — agora ITI, taxa geral indicada de 1% (3% em casos privilegiados); notario ~1–2%; registo ~2%. Guias antigos referem ~3% (regra IUP, anterior a 2026) — confirme os valores atuais.\n\nFontes: guias comerciais e eRegulations Cabo Verde. Nao oficial; verificacao necessaria.","en":"Indicative sequence (ASSUMPTION based on commercial guides — confirm):\n\n1) Obtain the NIF (tax number) at the tax office. Foreigners may buy property in Cape Verde.\n2) Request the Land-Registry Certificate to verify the description and any charges/mortgages.\n3) Recommended: grant power of attorney to a Cape Verdean lawyer.\n4) Sign the Promissory Purchase Contract (typical deposit 10–30%).\n5) Execute the Public Deed before a notary and pay the balance.\n6) Register the property in your name at the Land Registry.\n\nApproximate costs (INDICATIVE): transfer — now ITI, indicated standard rate 1% (3% in privileged cases); notary ~1–2%; registration ~2%. Older guides quote ~3% (the pre-2026 IUP rule) — confirm current figures.\n\nSources: commercial guides and eRegulations Cape Verde. Unofficial; verification required.","nl":"Indicatieve volgorde (AANNAME op basis van commerciele gidsen — bevestigen):\n\n1) Verkrijg het NIF (fiscaal nummer) bij het belastingkantoor. Buitenlanders mogen vastgoed kopen in Kaapverdie.\n2) Vraag het kadastrale uittreksel op om de omschrijving en eventuele lasten/hypotheken te controleren.\n3) Aanbevolen: geef een Kaapverdische advocaat volmacht.\n4) Teken het voorlopige koopcontract (gebruikelijke aanbetaling 10–30%).\n5) Verlijd de notariele akte en betaal het restant.\n6) Schrijf de eigendom op uw naam in bij het kadaster.\n\nGeschatte kosten (INDICATIEF): overdracht — nu ITI, aangegeven tarief 1% (3% in bevoorrechte gevallen); notaris ~1–2%; inschrijving ~2%. Oudere gidsen noemen ~3% (IUP-regel van voor 2026) — bevestig de actuele cijfers.\n\nBronnen: commerciele gidsen en eRegulations Kaapverdie. Niet officieel; verificatie vereist."}'::jsonb,
  'published', now()
)
on conflict (slug) do update set
  category = excluded.category,
  title = excluded.title,
  gov_entity = excluded.gov_entity,
  official_status = excluded.official_status,
  version = excluded.version,
  source_url = excluded.source_url,
  summary = excluded.summary,
  body = excluded.body,
  status = excluded.status,
  updated_at = now();
