-- 0020 — seed: São Vicente business directory ("phone book"), unclaimed.
-- Compiled from public sources on 2026-07-22. Every row is seeded (user_id null),
-- published, and carries its primary source. Owners can claim their profile
-- (migration 0019). Re-runnable: refreshes only still-unclaimed rows, never
-- overwrites a claimed profile. Run AFTER 0019.
-- Official government offices are intentionally excluded (official != commercial).

begin;

-- Professionals (legal, construction, trades, cleaning, gas) -----------------
insert into public.professionals
  (user_id, slug, display_name, headline, bio, category, service_areas, status, phone, source_name, source_url, sourced_at)
values
  (null, 'vanda-evora-onofre-lima-advogados', 'Vanda Évora & Onofre Lima, Sociedade de Advogados', '{"pt":"Sociedade de advogados em Mindelo","en":"Law firm in Mindelo","nl":"Advocatenkantoor in Mindelo"}'::jsonb, '{"pt":"Sociedade de advogados de Vanda Maria Lima Évora (cédula 036/01) e Manuel Onofre Lima (053/01), inscritos na Ordem dos Advogados de Cabo Verde. Mindelo, São Vicente. E-mail: onofreli@hotmail.com.","en":"Law partnership of Vanda Maria Lima Évora (bar no. 036/01) and Manuel Onofre Lima (053/01), registered with the Cape Verde Bar Association. Mindelo, São Vicente. Email: onofreli@hotmail.com.","nl":"Advocatenmaatschap van Vanda Maria Lima Évora (balienr. 036/01) en Manuel Onofre Lima (053/01), ingeschreven bij de Kaapverdische Orde van Advocaten. Mindelo, São Vicente. E-mail: onofreli@hotmail.com."}'::jsonb, 'Advogados', '{"São Vicente"}', 'published', '+238 232 32 78', 'Ordem dos Advogados de Cabo Verde (inscrição em vigor)', 'https://www.oacv.cv/images/PDF/AdComIncricao/06_07_26_AdvogadosComInscricaoVigor.pdf', '2026-07-22'::date),
  (null, 'egl-advogados-associados', 'EGL – Advogados Associados', '{"pt":"Escritório de advogados em Mindelo","en":"Law office in Mindelo","nl":"Advocatenkantoor in Mindelo"}'::jsonb, '{"pt":"Escritório de advogados (Belarmino Lucas 081/01, Ronise Pires Évora 065/01) na Rua Dr. António Aurélio Gonçalves n.º 7, Mindelo. E-mail: egl1@cvtelecom.cv.","en":"Law office (Belarmino Lucas 081/01, Ronise Pires Évora 065/01) at Rua Dr. António Aurélio Gonçalves no. 7, Mindelo. Email: egl1@cvtelecom.cv.","nl":"Advocatenkantoor (Belarmino Lucas 081/01, Ronise Pires Évora 065/01) aan Rua Dr. António Aurélio Gonçalves nr. 7, Mindelo. E-mail: egl1@cvtelecom.cv."}'::jsonb, 'Advogados', '{"São Vicente"}', 'published', '+238 232 34 21', 'Ordem dos Advogados de Cabo Verde (inscrição em vigor)', 'https://www.oacv.cv/images/PDF/AdComIncricao/06_07_26_AdvogadosComInscricaoVigor.pdf', '2026-07-22'::date),
  (null, 'claudia-vasconcelos-advogada', 'Cláudia Vasconcelos – Advocacia e Consultoria Jurídica', '{"pt":"Advogada (fala inglês) em Mindelo","en":"Lawyer (English-speaking) in Mindelo","nl":"Advocaat (spreekt Engels) in Mindelo"}'::jsonb, '{"pt":"Cláudia Maria Andrade Vasconcelos Lopes (cédula 148/05), advocacia e consultoria jurídica, Mindelo. Fala inglês. E-mail: claudinhavasconcelos@hotmail.com.","en":"Cláudia Maria Andrade Vasconcelos Lopes (bar no. 148/05), advocacy and legal consultancy, Mindelo. English-speaking. Email: claudinhavasconcelos@hotmail.com.","nl":"Cláudia Maria Andrade Vasconcelos Lopes (balienr. 148/05), advocatuur en juridisch advies, Mindelo. Spreekt Engels. E-mail: claudinhavasconcelos@hotmail.com."}'::jsonb, 'Advogados', '{"São Vicente"}', 'published', '+238 232 19 22', 'Ordem dos Advogados de Cabo Verde (inscrição em vigor)', 'https://www.oacv.cv/images/PDF/AdComIncricao/06_07_26_AdvogadosComInscricaoVigor.pdf', '2026-07-22'::date),
  (null, 'jose-pedro-da-luz-advogado', 'José Pedro da Luz – Advogado', '{"pt":"Advogado em Mindelo","en":"Lawyer in Mindelo","nl":"Advocaat in Mindelo"}'::jsonb, '{"pt":"José Pedro da Luz (cédula 034/01), Rua Angola n.º 1, Mindelo. E-mail: jpluz@cvtelecom.cv.","en":"José Pedro da Luz (bar no. 034/01), Rua Angola no. 1, Mindelo. Email: jpluz@cvtelecom.cv.","nl":"José Pedro da Luz (balienr. 034/01), Rua Angola nr. 1, Mindelo. E-mail: jpluz@cvtelecom.cv."}'::jsonb, 'Advogados', '{"São Vicente"}', 'published', '+238 232 84 85', 'Ordem dos Advogados de Cabo Verde (inscrição em vigor)', 'https://www.oacv.cv/images/PDF/AdComIncricao/06_07_26_AdvogadosComInscricaoVigor.pdf', '2026-07-22'::date),
  (null, 'armindo-santos-cruz-advogado', 'Armindo Santos Cruz – Advocacia e Consultoria', '{"pt":"Advogado em Mindelo","en":"Lawyer in Mindelo","nl":"Advocaat in Mindelo"}'::jsonb, '{"pt":"Armindo Santos Cruz (cédula 037/01), Av. Dr. Baltazar Lopes da Silva n.º 29, 2.º, Mindelo. E-mail: arsacruz@hotmail.com.","en":"Armindo Santos Cruz (bar no. 037/01), Av. Dr. Baltazar Lopes da Silva no. 29, 2nd floor, Mindelo. Email: arsacruz@hotmail.com.","nl":"Armindo Santos Cruz (balienr. 037/01), Av. Dr. Baltazar Lopes da Silva nr. 29, 2e verd., Mindelo. E-mail: arsacruz@hotmail.com."}'::jsonb, 'Advogados', '{"São Vicente"}', 'published', '+238 232 44 65', 'Ordem dos Advogados de Cabo Verde (inscrição em vigor)', 'https://www.oacv.cv/images/PDF/AdComIncricao/06_07_26_AdvogadosComInscricaoVigor.pdf', '2026-07-22'::date),
  (null, 'silvestre-beneditino-evora-advogado', 'Silvestre Beneditino Évora – Advogado', '{"pt":"Advogado em Mindelo","en":"Lawyer in Mindelo","nl":"Advocaat in Mindelo"}'::jsonb, '{"pt":"Silvestre Beneditino Évora (cédula 007/01), Rua 19 de Setembro, Mindelo.","en":"Silvestre Beneditino Évora (bar no. 007/01), Rua 19 de Setembro, Mindelo.","nl":"Silvestre Beneditino Évora (balienr. 007/01), Rua 19 de Setembro, Mindelo."}'::jsonb, 'Advogados', '{"São Vicente"}', 'published', '+238 232 18 64', 'Ordem dos Advogados de Cabo Verde (inscrição em vigor)', 'https://www.oacv.cv/images/PDF/AdComIncricao/06_07_26_AdvogadosComInscricaoVigor.pdf', '2026-07-22'::date),
  (null, 'carla-mendes-advogada', 'Carla Mendes – Advogada', '{"pt":"Advogada em Mindelo","en":"Lawyer in Mindelo","nl":"Advocaat in Mindelo"}'::jsonb, '{"pt":"Carla Maria Jesus Mendes (cédula 366/16), Rua de Coco, Mindelo. Horário seg.–sex. 08:00–18:00.","en":"Carla Maria Jesus Mendes (bar no. 366/16), Rua de Coco, Mindelo. Hours Mon–Fri 08:00–18:00.","nl":"Carla Maria Jesus Mendes (balienr. 366/16), Rua de Coco, Mindelo. Openingstijden ma–vr 08:00–18:00."}'::jsonb, 'Advogados', '{"São Vicente"}', 'published', '+238 988 87 62', 'Ordem dos Advogados de Cabo Verde (inscrição em vigor)', 'https://www.oacv.cv/images/PDF/AdComIncricao/06_07_26_AdvogadosComInscricaoVigor.pdf', '2026-07-22'::date),
  (null, 'despachante-carlos-monteiro-fernandes', 'Despachante Oficial Carlos Monteiro Fernandes', '{"pt":"Despachante oficial (desalfandegamento) em Mindelo","en":"Licensed customs broker in Mindelo","nl":"Beëdigd douaneagent in Mindelo"}'::jsonb, '{"pt":"Despachante oficial (cédula n.º 80, 2012): desalfandegamento e documentação para a alfândega, porto (ENAPOR) e aeroporto de São Vicente. Rua Cristiano Sena Barcelos n.º 27, Mindelo. E-mail: geral@despachanteoficial.cv.","en":"Licensed customs broker (licence no. 80, 2012): customs clearance and trade documentation for São Vicente customs, port (ENAPOR) and airport. Rua Cristiano Sena Barcelos no. 27, Mindelo. Email: geral@despachanteoficial.cv.","nl":"Beëdigd douaneagent (vergunning nr. 80, 2012): inklaring en handelsdocumentatie voor de douane, haven (ENAPOR) en luchthaven van São Vicente. Rua Cristiano Sena Barcelos nr. 27, Mindelo. E-mail: geral@despachanteoficial.cv."}'::jsonb, 'Despachante oficial', '{"São Vicente"}', 'published', '+238 232 58 89', 'Website oficial (despachanteoficial.cv)', 'https://www.despachanteoficial.cv/', '2026-07-22'::date),
  (null, 'armando-cunha-cabo-verde', 'Armando Cunha, Cabo Verde, S.A.', '{"pt":"Construção civil e obras públicas","en":"Civil construction and public works","nl":"Civiele bouw en openbare werken"}'::jsonb, '{"pt":"Empresa de construção civil e obras públicas (desde 2007) com sede em Mindelo e estaleiro na Zona Industrial do Lazareto; alvará de construção válido. Estradas, edifícios e obras marítimas e urbanas. E-mail: geral@armandocunha.cv.","en":"Civil-construction and public-works company (since 2007), HQ in Mindelo with a yard in the Lazareto industrial zone; valid construction licence. Roads, buildings, maritime and urban works. Email: geral@armandocunha.cv.","nl":"Bedrijf voor civiele bouw en openbare werken (sinds 2007), hoofdkantoor in Mindelo met werkplaats op het industrieterrein Lazareto; geldige bouwvergunning. Wegen, gebouwen, maritieme en stedelijke werken. E-mail: geral@armandocunha.cv."}'::jsonb, 'Construção civil', '{"São Vicente"}', 'published', '+238 231 96 77', 'IGOTCI — lista de alvarás válidos (Fev 2025) + website oficial', 'https://armandocunha.cv/contactos/', '2026-07-22'::date),
  (null, 'sina-construcoes', 'SINA Construções, Lda', '{"pt":"Construção civil e obras públicas em Mindelo","en":"Civil construction and public works in Mindelo","nl":"Civiele bouw en openbare werken in Mindelo"}'::jsonb, '{"pt":"Sociedade de Investimentos Nacional — construção civil em Mindelo: edifícios, escolas, estradas, saneamento e reabilitação. Alvará de construção válido (Classe 5). E-mail: sina@sina.cv.","en":"Sociedade de Investimentos Nacional — civil construction in Mindelo: buildings, schools, roads, sanitation and rehabilitation. Valid construction licence (Class 5). Email: sina@sina.cv.","nl":"Sociedade de Investimentos Nacional — civiele bouw in Mindelo: gebouwen, scholen, wegen, sanitatie en renovatie. Geldige bouwvergunning (Klasse 5). E-mail: sina@sina.cv."}'::jsonb, 'Construção civil', '{"São Vicente"}', 'published', '+238 230 05 50', 'IGOTCI — lista de alvarás válidos (Fev 2025) + website oficial', 'https://sina.cv/', '2026-07-22'::date),
  (null, 'sci-spencer-construcoes-mindelo', 'SCI – Spencer Construções & Imobiliária, Lda (Mindelo)', '{"pt":"Construção civil e imobiliária — balcão de Mindelo","en":"Construction & real estate — Mindelo branch","nl":"Bouw & vastgoed — vestiging Mindelo"}'::jsonb, '{"pt":"Construção civil, obras públicas, projeto, blocos e alumínio/ferro (desde 2006). Balcão de São Vicente: Rua Baltazar Lopes da Silva n.º 51 (ao lado da Electra), Mindelo. Alvará válido (Classe 7). E-mail: sci@cvtelecom.cv.","en":"Civil construction, public works, design, blocks and aluminium/iron (since 2006). São Vicente branch: Rua Baltazar Lopes da Silva no. 51 (next to Electra), Mindelo. Valid licence (Class 7). Email: sci@cvtelecom.cv.","nl":"Civiele bouw, openbare werken, ontwerp, blokken en aluminium/ijzer (sinds 2006). Vestiging São Vicente: Rua Baltazar Lopes da Silva nr. 51 (naast Electra), Mindelo. Geldige vergunning (Klasse 7). E-mail: sci@cvtelecom.cv."}'::jsonb, 'Construção civil', '{"São Vicente"}', 'published', '+238 232 56 56', 'IGOTCI — lista de alvarás válidos (Fev 2025) + website oficial', 'http://www.sci.cv/', '2026-07-22'::date),
  (null, 'cmcv-construcoes-metalicas', 'Construções Metálicas de Cabo Verde, Lda (CMCV)', '{"pt":"Serralharia e estruturas metálicas (desde 2000)","en":"Metalwork and steel structures (since 2000)","nl":"Metaalbouw en staalconstructies (sinds 2000)"}'::jsonb, '{"pt":"Fabrico e montagem de estruturas metálicas e serralharia em ferro, inox e alumínio; reparação naval e tratamento de superfícies. Zona Industrial da Ribeira de Julião, São Vicente. Certificação ISO 9001. Orçamentos: orcamentos@cmcvlda.cv.","en":"Fabrication and installation of steel structures and ironwork in iron, stainless steel and aluminium; naval repair and surface treatment. Ribeira de Julião industrial zone, São Vicente. ISO 9001 certified. Quotes: orcamentos@cmcvlda.cv.","nl":"Fabricage en montage van staalconstructies en metaalwerk in ijzer, rvs en aluminium; scheepsreparatie en oppervlaktebehandeling. Industrieterrein Ribeira de Julião, São Vicente. ISO 9001-gecertificeerd. Offertes: orcamentos@cmcvlda.cv."}'::jsonb, 'Serralharia / metalomecânica', '{"São Vicente"}', 'published', '+238 232 44 00', 'IGOTCI + Câmara de Comércio do Barlavento + website oficial', 'https://cmcvlda.cv/', '2026-07-22'::date),
  (null, 'ramos-castellano-arquitectos', 'Ramos Castellano Arquitectos', '{"pt":"Atelier de arquitetura em Mindelo","en":"Architecture studio in Mindelo","nl":"Architectenbureau in Mindelo"}'::jsonb, '{"pt":"Atelier de arquitetura (desde 2005) de Eloisa Ramos e Moreno Castellano, Mindelo. Obras publicadas internacionalmente (CNAD, Terra Lodge, Casa Celestina). Av. 5 de Julho 18. Contacto: info@ramoscastellano.com.","en":"Architecture studio (since 2005) of Eloisa Ramos and Moreno Castellano, Mindelo. Internationally published work (CNAD, Terra Lodge, Casa Celestina). Av. 5 de Julho 18. Contact: info@ramoscastellano.com.","nl":"Architectenbureau (sinds 2005) van Eloisa Ramos en Moreno Castellano, Mindelo. Internationaal gepubliceerd werk (CNAD, Terra Lodge, Casa Celestina). Av. 5 de Julho 18. Contact: info@ramoscastellano.com."}'::jsonb, 'Arquitetura', '{"São Vicente"}', 'published', null, 'Website oficial (ramoscastellano.com)', 'https://ramoscastellano.com/contact/', '2026-07-22'::date),
  (null, 'oficina-de-utopias', 'Oficina de Utopias', '{"pt":"Arquitetura, arte e design em Mindelo","en":"Architecture, art and design in Mindelo","nl":"Architectuur, kunst en design in Mindelo"}'::jsonb, '{"pt":"Atelier (desde 2015) de Ângelo Lopes e Rita Rainho: arquitetura, arte e design. Av. Abílio Duarte n.º 32, Mindelo. Projeto Slat House publicado na ArchDaily (2024). E-mail: oficinadeutopias@gmail.com.","en":"Studio (since 2015) of Ângelo Lopes and Rita Rainho: architecture, art and design. Av. Abílio Duarte no. 32, Mindelo. Slat House project published on ArchDaily (2024). Email: oficinadeutopias@gmail.com.","nl":"Studio (sinds 2015) van Ângelo Lopes en Rita Rainho: architectuur, kunst en design. Av. Abílio Duarte nr. 32, Mindelo. Slat House-project gepubliceerd op ArchDaily (2024). E-mail: oficinadeutopias@gmail.com."}'::jsonb, 'Arquitetura', '{"São Vicente"}', 'published', '+238 981 44 88', 'Website oficial + ArchDaily (2024)', 'https://www.oficinadeutopias.com/en/sobre', '2026-07-22'::date),
  (null, 'soteclima', 'Soteclima, Lda', '{"pt":"Ar condicionado e ventilação em Mindelo","en":"Air conditioning and ventilation in Mindelo","nl":"Airco en ventilatie in Mindelo"}'::jsonb, '{"pt":"Venda, instalação e manutenção de ar condicionado (splits, VRV, chillers), ventilação, extração de fumos e solar térmico. Instalador autorizado General Fujitsu, Daitsu e Sodeca. Chã de Alecrim, Mindelo. E-mail: soteclima@soteclima.cv.","en":"Sale, installation and maintenance of air conditioning (splits, VRV, chillers), ventilation, smoke extraction and solar-thermal. Authorised installer for General Fujitsu, Daitsu and Sodeca. Chã de Alecrim, Mindelo. Email: soteclima@soteclima.cv.","nl":"Verkoop, installatie en onderhoud van airco (splits, VRV, chillers), ventilatie, rookafvoer en zonneboilers. Erkend installateur van General Fujitsu, Daitsu en Sodeca. Chã de Alecrim, Mindelo. E-mail: soteclima@soteclima.cv."}'::jsonb, 'Climatização / AVAC', '{"São Vicente"}', 'published', '+238 353 22 07', 'Website oficial (soteclima.cv)', 'https://soteclima.cv/contactos/', '2026-07-22'::date),
  (null, 'sossir-limpeza', 'SOSSIR, Lda', '{"pt":"Limpeza industrial e mecanizada (desde 1996)","en":"Industrial & mechanised cleaning (since 1996)","nl":"Industriële & machinale reiniging (sinds 1996)"}'::jsonb, '{"pt":"Serviços de limpeza industrial e mecanizada em São Vicente desde 1996. Av. 5 de Julho, Porta 25, Mindelo. E-mail: sossirlimitada@gmail.com.","en":"Industrial and mechanised cleaning services in São Vicente since 1996. Av. 5 de Julho, Porta 25, Mindelo. Email: sossirlimitada@gmail.com.","nl":"Industriële en machinale schoonmaakdiensten in São Vicente sinds 1996. Av. 5 de Julho, Porta 25, Mindelo. E-mail: sossirlimitada@gmail.com."}'::jsonb, 'Limpeza', '{"São Vicente"}', 'published', '+238 232 78 28', 'Câmara de Comércio do Barlavento + website oficial', 'https://www.camara.cv/associados/vitrina-de-associados/sossir-lda/', '2026-07-22'::date),
  (null, 'boavista-limpeza', 'Boavista Limpeza', '{"pt":"Serviço de limpeza em Mindelo","en":"Cleaning service in Mindelo","nl":"Schoonmaakdienst in Mindelo"}'::jsonb, '{"pt":"Serviço de limpeza (e produtos de limpeza), Rua Argélia 81, junto à Praça Nova, Mindelo. Horário seg.–sáb.","en":"Cleaning service (and cleaning products), Rua Argélia 81, next to Praça Nova, Mindelo. Open Mon–Sat.","nl":"Schoonmaakdienst (en schoonmaakproducten), Rua Argélia 81, naast Praça Nova, Mindelo. Open ma–za."}'::jsonb, 'Limpeza', '{"São Vicente"}', 'published', '+238 231 76 77', 'AfricaBizInfo + Cleaners10 (listagens públicas)', 'https://www.africabizinfo.com/pt-CV/boavista-limpeza', '2026-07-22'::date),
  (null, 'enacol-gas-mindelo', 'Enacol, S.A. — gás (Mindelo)', '{"pt":"Gás butano e entrega ao domicílio em Mindelo","en":"Butane gas and home delivery in Mindelo","nl":"Butaangas en thuisbezorging in Mindelo"}'::jsonb, '{"pt":"Empresa nacional de combustíveis, com sede em Mindelo. Venda de gás butano e entrega ao domicílio (linha 430 60 60). Pontos de venda em São Vicente (Ribeira Julião, Madeiralzinho 24h, Monte). E-mail: energia@enacol.cv.","en":"National fuel company, headquartered in Mindelo. Butane-gas sales and home delivery (line 430 60 60). São Vicente sales points (Ribeira Julião, Madeiralzinho 24h, Monte). Email: energia@enacol.cv.","nl":"Nationaal brandstofbedrijf, hoofdkantoor in Mindelo. Verkoop van butaangas en thuisbezorging (lijn 430 60 60). Verkooppunten op São Vicente (Ribeira Julião, Madeiralzinho 24u, Monte). E-mail: energia@enacol.cv."}'::jsonb, 'Gás', '{"São Vicente"}', 'published', '+238 430 60 60', 'Website oficial (enacol.cv)', 'https://www.enacol.cv/contactos-enacol/', '2026-07-22'::date),
  (null, 'vivo-energy-shell-mindelo', 'Vivo Energy Cabo Verde (Shell) — Mindelo', '{"pt":"Gás Shell e combustíveis — sede em Mindelo","en":"Shell gas and fuels — HQ in Mindelo","nl":"Shell-gas en brandstoffen — kantoor in Mindelo"}'::jsonb, '{"pt":"Licenciada da Shell em Cabo Verde, sede em Mindelo (Av. Amílcar Cabral). Gás butano (botija) e entrega ao domicílio Shell Gás; combustíveis e lubrificantes.","en":"Shell licensee in Cape Verde, HQ in Mindelo (Av. Amílcar Cabral). Butane gas (botija) with Shell Gás home delivery; fuels and lubricants.","nl":"Shell-licentiehouder in Kaapverdië, kantoor in Mindelo (Av. Amílcar Cabral). Butaangas (botija) met Shell Gás-thuisbezorging; brandstoffen en smeermiddelen."}'::jsonb, 'Gás', '{"São Vicente"}', 'published', '+238 230 76 00', 'Vivo Energy (site oficial) + Câmara de Comércio do Barlavento', 'https://www.vivoenergy.com/en/contacts', '2026-07-22'::date),
  (null, 'estacao-shell-rua-da-praia', 'Estação Shell Rua da Praia (M. Araújo)', '{"pt":"Estação Shell (gás e combustíveis) na Rua da Praia","en":"Shell station (gas and fuels) on Rua da Praia","nl":"Shell-station (gas en brandstof) aan Rua da Praia"}'::jsonb, '{"pt":"Estação de serviço Shell na Rua da Praia, Mindelo: combustíveis, lubrificantes e gás, com serviços ao veículo. E-mail: shellruadapraia@gmail.com.","en":"Shell service station on Rua da Praia, Mindelo: fuels, lubricants and gas, with vehicle services. Email: shellruadapraia@gmail.com.","nl":"Shell-servicestation aan Rua da Praia, Mindelo: brandstoffen, smeermiddelen en gas, met voertuigservice. E-mail: shellruadapraia@gmail.com."}'::jsonb, 'Gás / combustíveis', '{"São Vicente"}', 'published', '+238 232 30 04', 'Website oficial (shellruadapraia.cv)', 'https://shellruadapraia.cv/contactos-uteis/', '2026-07-22'::date)
on conflict (slug) do update set
  display_name = excluded.display_name, headline = excluded.headline, bio = excluded.bio,
  category = excluded.category, phone = excluded.phone, service_areas = excluded.service_areas,
  status = excluded.status, source_name = excluded.source_name, source_url = excluded.source_url,
  sourced_at = excluded.sourced_at
where professionals.user_id is null and professionals.claimed_at is null;

-- Suppliers (materials / hardware / paint) -----------------------------------
insert into public.suppliers
  (user_id, slug, name, category, island, description, status, phone, verified, source_name, source_url, sourced_at)
values
  (null, 'mj-materiais-de-construcao', 'MJ – Materiais de Construção', '{"pt":"Materiais de construção","en":"Building materials","nl":"Bouwmaterialen"}'::jsonb, 'São Vicente', '{"pt":"Loja de materiais de construção com loja online, na Av. Manuel Matos n.º 13, Mindelo (e 2.ª loja na Rua 19 de Setembro). Materiais, loiças e eletrodomésticos. Linha cliente 986 79 59. E-mail: loja.online@mj.cv.","en":"Building-materials store with online shop, Av. Manuel Matos no. 13, Mindelo (and a 2nd store on Rua 19 de Setembro). Materials, fixtures and appliances. Customer line 986 79 59. Email: loja.online@mj.cv.","nl":"Bouwmaterialenwinkel met webshop, Av. Manuel Matos nr. 13, Mindelo (en 2e winkel aan Rua 19 de Setembro). Materialen, sanitair en apparatuur. Klantenlijn 986 79 59. E-mail: loja.online@mj.cv."}'::jsonb, 'published', '+238 231 90 21', false, 'Website oficial (mj.cv)', 'https://mj.cv/contactos/', '2026-07-22'::date),
  (null, 'jbc-joao-benoliel-de-carvalho', 'JBC – João Benoliel de Carvalho, Lda', '{"pt":"Materiais de construção","en":"Building materials","nl":"Bouwmaterialen"}'::jsonb, 'São Vicente', '{"pt":"Casa fundada em 1927, sede em São Vicente: importação e venda de materiais de construção (ferragens, vidro, loiça sanitária) e eletrodomésticos, com lojas em Mindelo. E-mail: jbc_sv@cvtelecom.cv.","en":"Company founded in 1927, HQ in São Vicente: import and sale of construction materials (hardware, glass, sanitary ware) and appliances, with stores in Mindelo. Email: jbc_sv@cvtelecom.cv.","nl":"Bedrijf opgericht in 1927, hoofdkantoor op São Vicente: import en verkoop van bouwmaterialen (ijzerwaren, glas, sanitair) en apparatuur, met winkels in Mindelo. E-mail: jbc_sv@cvtelecom.cv."}'::jsonb, 'published', '+238 231 63 56', false, 'Câmara de Comércio do Barlavento + Mindel Insite', 'https://www.camara.cv/associados/vitrina-de-associados/joao-benoliel-de-carvalho-lda/', '2026-07-22'::date),
  (null, 'prolar-materiais', 'Prolar – Materiais, Soluções e Serviços, Lda', '{"pt":"Materiais de construção","en":"Building materials","nl":"Bouwmaterialen"}'::jsonb, 'São Vicente', '{"pt":"Importação e venda de materiais de construção (ferragens, vidro, loiça sanitária) desde 2015. Ribeirinha, Mindelo. E-mail: prolarcv@gmail.com.","en":"Import and sale of construction materials (hardware, glass, sanitary ware) since 2015. Ribeirinha, Mindelo. Email: prolarcv@gmail.com.","nl":"Import en verkoop van bouwmaterialen (ijzerwaren, glas, sanitair) sinds 2015. Ribeirinha, Mindelo. E-mail: prolarcv@gmail.com."}'::jsonb, 'published', '+238 232 35 50', false, 'Câmara de Comércio do Barlavento + website oficial', 'https://prolar.cv/', '2026-07-22'::date),
  (null, 'bricodelo-ferramentas', 'Bricodelo – Comércio, Lda', '{"pt":"Ferragens e ferramentas","en":"Hardware and tools","nl":"IJzerwaren en gereedschap"}'::jsonb, 'São Vicente', '{"pt":"Loja de materiais elétricos e ferramentas (desde 2020) com loja online, Rua Franz Fanon, Mindelo. Ferramentas elétricas e manuais, iluminação, EPI e canalização.","en":"Electrical-materials and tools store (since 2020) with online shop, Rua Franz Fanon, Mindelo. Power and hand tools, lighting, PPE and plumbing supplies.","nl":"Winkel voor elektrisch materiaal en gereedschap (sinds 2020) met webshop, Rua Franz Fanon, Mindelo. Elektrisch en handgereedschap, verlichting, PBM en loodgietersbenodigdheden."}'::jsonb, 'published', null, false, 'Website oficial (bricodelo.cv)', 'https://bricodelo.cv/pt/company', '2026-07-22'::date),
  (null, 'sita-tintas-mindelo', 'SITA – Tintas (delegação de São Vicente)', '{"pt":"Tintas","en":"Paint","nl":"Verf"}'::jsonb, 'São Vicente', '{"pt":"Fabricante de tintas de Cabo Verde, com delegação em São Vicente e lojas Colorshop em Mindelo (Rua do Côco e Carreira de Tiro). Loja online. E-mail: comercial@sita.cv.","en":"Cape Verde paint manufacturer, with a São Vicente delegation and Colorshop stores in Mindelo (Rua do Côco and Carreira de Tiro). Online shop. Email: comercial@sita.cv.","nl":"Kaapverdische verffabrikant, met een vestiging op São Vicente en Colorshop-winkels in Mindelo (Rua do Côco en Carreira de Tiro). Webshop. E-mail: comercial@sita.cv."}'::jsonb, 'published', '+238 262 72 74', false, 'Website oficial (sita.cv)', 'https://sita.cv/', '2026-07-22'::date)
on conflict (slug) do update set
  name = excluded.name, category = excluded.category, island = excluded.island,
  description = excluded.description, phone = excluded.phone, status = excluded.status,
  source_name = excluded.source_name, source_url = excluded.source_url, sourced_at = excluded.sourced_at
where suppliers.user_id is null and suppliers.claimed_at is null;

commit;
